port: 7890
socks-port: 7891

# redir port for Linux and macOS
redir-port: 7892

# `allow-lan` must be true in your config.yaml
allow-lan: true
external-controller: 0.0.0.0:9090

# dashboard folder
# external-ui: /ui
